settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: default
  path: .
  commands:
    install:
      status: true
      method: go build -o ./bin
    run:
      status: true
      method: ./bin
  watcher:
    extensions:
    - go
    paths:
    - ../../../default
    - ../../../src
    ignored_paths:
    - .git
    - .realize
    - vender
    - go.mod
    - go.sum
